using System;
using UnityEngine;

public class View : MonoBehaviour
{
    public Transform player;
    public float sens;
    float xRotation = 0f;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Cursor.lockState= CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        float mouseX= Input.GetAxis("Mouse X")*sens*Time.deltaTime;
        float mouseY= Input.GetAxis("Mouse Y")*sens*Time.deltaTime;

        xRotation -= mouseY;
        xRotation= Mathf.Clamp(xRotation, -90f, 90f);
        
        transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f);
        player.Rotate(Vector3.up * mouseX);
    }
}
